version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=staccato
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '33060:33060'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    container_name: staccato-backend
    build:
      context: ./
      target: production
    image: staccato-backend
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: staccato
    links:
      - db
    volumes:
      - ./:/src
volumes:
  db:
    driver: local